version: '3.8'

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./env/.production.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8080:8080
    command: yarn prisma:prod:deploy
    restart: always
  
  postgres:
    image: postgres:15
    container_name: postgreprisma
    restart: always
    ports:
      - 5434:5432
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: meetup
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
