version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .docker.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8080:8080
      - 9229:9229
    command: yarn start:docker
    restart: always
volumes:
  pgdata:
